export enum CommentError {
    DRIVER_NOT_FOUND = "DRIVER_NOT_FOUND", 
    DRIVER_IS_SAME_TO_COMMENT = "DRIVER_IS_SAME_TO_COMMENT", 
    USER_DID_NOT_RIDE_WITH_DRIVER = "USER_DID_NOT_RIDE_WITH_DRIVER", 
    COMMENT_NOT_FOUND = "COMMENT_NOT_FOUND", 
    USER_ALREADY_COMMENTED_ON_DRIVER = "USER_ALREADY_COMMENTED_ON_DRIVER", 
}